### ISSUE TITLE
Fix pylint issues in webapp

### ISSUE THREAD

**Issue by MichaelMraka** [RedHatInsights/vmaas#120]
Currently I've (temporarily!) disabled pylint warnings in webapp:
************* Module errata
R: 10, 4: Too many arguments (9/5) (too-many-arguments)
R: 97, 4: Too many local variables (18/15) (too-many-locals)
************* Module updates
R: 73, 4: Too many local variables (57/15) (too-many-locals)
R:271, 8: Too many nested blocks (8/5) (too-many-nested-blocks)
R: 73, 4: Too many branches (49/12) (too-many-branches)
R: 73, 4: Too many statements (134/50) (too-many-statements)

Needs to be resolved and remove '#pylint disable' comments.

**Comment by eherget** [comment]
This issue was to resolve pylint issues in webapp.  Specifically, to make modifications so that "# pylint disable:..." comments were no longer necessary.

I had done some work on this previously (on the errata api), and then put it on hold as we prepared for the Insights demo at the Red Hat conference.  Now that the demo is over, I'm questioning if there is still a need for this work.  We have several "#pylint disable:..." comments throughout the code for things like too-many-arguments, too-many-locals, too-many branches, etc. Refactoring the code to get rid of the need for *all* of these pylint disable comments seems like a lot of work, for not much gain, and might result in some unnecessary things like adding extra class methods just for the sake of dropping a pylint warning.

My suggestion would be to close this issue as overly broad.  Going forward, we would open issues for specific pylint warnings we believe indicates an actual issue we should address.

**Comment by MichaelMraka** [comment]
I agree.
I'd also globally disable some more standard pylint checks we don't enforce (e.g. too-few-public-methods - disabled 12 times, too-many-locals - 6 times, too-many-arguments 5 times)...

**Comment by ggainey** [comment]
General issue addressed in #283
