### ISSUE TITLE
reposcan: deduplicate code

### ISSUE THREAD

**Issue by MichaelMraka** [RedHatInsights/vmaas#147]
Similar code for  table of keys (e.g. severity) handling is used both in reposcan and cve scan. We should merge implementations into a single one used in all places.

**Comment by jdobes** [comment]
Yes, they use the same table intentionally. Maybe it's not completely correct but it's not a bug either.

**Comment by eherget** [comment]
Since the values for these two separate fields are defined by errata and CVE specs, we should implement these as separate, static tables defined during database initialization.  In addition to avoiding confusion of having two separate fields in one keyword/mapping table, it also ensures the id-to-text mapping always uses the same id values, which allows the ids to be defined in a useful order to allow for sorting by severity or impact.
