### ISSUE TITLE
CVE impact - empty string instead of "low"

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/vmaas#206]
```
curl -X GET "http://webapp-vmaas-stable.1b13.insights.openshiftapps.com/api/v1/cves/CVE-2014-7970" -H "accept: application/json"
```
returns
```
{
  "cve_list": {
    "CVE-2014-7970": {
      "impact": "",
      "public_date": "2014-10-13T10:55:00+00:00",
      "synopsis": "CVE-2014-7970",
      "description": "The pivot_root implementation in fs/namespace.c in the Linux kernel through 3.17 does not properly interact with certain locations of a chroot directory, which allows local users to cause a denial of service (mount-tree loop) via . (dot) values in both arguments to the pivot_root system call.",
      "modified_date": "2018-01-05T02:29:00+00:00",
      "redhat_url": "https://access.redhat.com/security/cve/cve-2014-7970",
      "cvss3_score": "",
      "secondary_url": "http://lists.opensuse.org/opensuse-security-announce/2015-04/msg00015.html",
      "cwe_list": [
        "CWE-399"
      ]
    }
  }
}
```

even though impact is defined as Low here: https://access.redhat.com/security/cve/cve-2014-7970

Looks like this is a general problem that applies to all CVEs of impact "Low"

**Comment by eherget** [comment]
As pointed out above, our cve info says it's impact is "Low".  However, the NVD-CVE info says it is "Medium" - https://nvd.nist.gov/vuln/detail/CVE-2014-7970

I pulled out the data we parse to populate this CVE and found this 'impact' data:

'impact': {'baseMetricV2': {'cvssV2': {'version': '2.0', 'vectorString': '(AV:L/AC:L/Au:N/C:N/I:N/A:C)', 'accessVector': 'LOCAL', 'accessComplexity': 'LOW', 'authentication': 'NONE', 'confidentialityImpact': 'NONE', 'integrityImpact': 'NONE', 'availabilityImpact': 'COMPLETE', 'baseScore': 4.9}, 'severity': 'MEDIUM', 'exploitabilityScore': 3.9, 'impactScore': 6.9, 'obtainAllPrivilege': False, 'obtainUserPrivilege': False, 'obtainOtherPrivilege': False, 'userInteractionRequired': False}}

However, our cve_store.py is looking for _dget(cve, "impact", "baseMetricV3", "cvssV3", "baseSeverity")

So I am making a guess here that we are only looking for cvssV3 data and not cvssV2.

In addition, this suggests we may have an issue populating CVE data from the combination of NIST and RedHat CVE data, since Red Hat says this CVE has 'Low' impact, while NIST says it has 'MEDIUM' impact.

**Comment by eherget** [comment]
Should we be parsing cvssV2 data if cvssV3 is not present?
