### ISSUE TITLE
reposcan: It always returns a successful result even if it fails immediately

### ISSUE THREAD

**Issue by grinrag** [RedHatInsights/vmaas#219]
If I pass malformed JSON via POST request I see a "success" as returned value:
{"msg": "Repo sync task started.", "success": true}

but in logs of reposcan container I see:

`json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 7952 (char 7951)`

**Comment by eherget** [comment]
I submitted a malformed JSON via POST (added a comma ',' after the opening '[{' in the file) and got a failure message:
curl -d @/home/rdu/eherget/vmaas/reposcan-bad.json  -X POST http://localhost:8081/api/v1/sync/repo
{"msg": "Incorrect JSON format.", "success": false}

Possibly there is a more specific malformed json you're sending?  If you can reproduce, please include the malformed json.  Otherwise, maybe this got fixed with some other PR?

**Comment by grinrag** [comment]
I rebased my local branch on upstream master and now I cannot reproduce the bug, see a correct behavior:
{"msg": "Incorrect JSON format.", "success": false}

So, closing the issue.
