### ISSUE TITLE
reposcan: support configuration of values

### ISSUE THREAD

**Issue by jdobes** [RedHatInsights/vmaas#23]
There are (and will be) some hard coded values in code like number of threads to download etc. that are good to be configurable using some config file or some container-friendly way.

**Comment by jdobes** [comment]
In docker are commonly used env variables for configuration.

**Comment by ggainey** [comment]
Candidates so far:

Definitely should be configurable:
downloader.py THREADS

Maybe configurable?
downloader/unpacker.py CHUNK_SIZE (at minimum, get this from one place instead of two)
batch_list.py DEFAULT_BATCH_SIZE
cve_controller.py YEAR_SINCE

Probably not useful:
downloader.py VALID_HTTP_CODES 
package_store.py CHECKSUM_TYPE_ALIASES

jdobes - thoughts?

**Comment by jdobes** [comment]
THREADS, CHUNK_SIZE, DEFAULT_BATCH_SIZE and YEAR_SINCE makes sense to make configurable using `vmaas/conf/reposcan.env`
