### ISSUE TITLE
Empty package_list in /cves

### ISSUE THREAD

**Issue by psegedy** [RedHatInsights/vmaas#380]
For some CVEs the `package_list` is empty even though this CVE should be associated with some packages. It happens when erratum doesn't have this CVE in `cve_list` but it fixes particular CVE.

For example https://access.redhat.com/errata/RHSA-2018:0029 fixes `CVE-2017-5715`, but list of CVEs is empty, so `RHSA-2018:0029` is not associated with `CVE-2017-5715`.

Because of that I can't find what packages are affected by `CVE-2017-5715`.

**Comment by ggainey** [comment]
This can't be a bug for vmaas. If Red Hat has not officially linked RPMs to an erratum, there isn't anything vmaas can do to find them. This problem is addressed by the rules implemented by insights-core, not by vmaas.

**Comment by jsvob** [comment]
> This can't be a bug for vmaas. If Red Hat has not officially linked RPMs to an erratum, there isn't anything vmaas can do to find them.

Is there a proper place where to report this, please?

> This problem is addressed by the rules implemented by insights-core, not by vmaas.

Can you please elaborate on what this means, or point me to the source code? I'd like to understand the broader concept and how it might affect us (ProdSec Insights rule devs).

**Comment by ggainey** [comment]
>> This can't be a bug for vmaas. If Red Hat has not officially linked RPMs to an erratum, there isn't anything vmaas can do to find them.

^RPMs^CVEs - apologies, wrong acronym up there.

> Is there a proper place where to report this, please?

Red Hat Product Security decided not to associate that particular CVE with any particular erratum, because (last I heard, anyway) it was possible that the CVE wasn't completely addressed yet and they did not want to give the impression that there was a complete fix. This isn't a problem - it's the reality of messy data from a messy real world :)

>> This problem is addressed by the rules implemented by insights-core, not by vmaas.

> Can you please elaborate on what this means, or point me to the source code? I'd like to understand the broader concept and how it might affect us (ProdSec Insights rule devs).

The advantage of the rules-based approach is that the rules-writers can 'know things' that the metadata doesn't, and therefore show *implied* relationships that the RPM-to-erratum and erratum-to-CVE metadata does not. vmaas-the-service can't - it only has available to it, the linkages that are explicit in the metadata. So there is a class of problem vmaas is good for, and a class of problem that rules are good for.

**Comment by jsvob** [comment]
>>> This problem is addressed by the rules implemented by insights-core, not by vmaas.

>> Can you please elaborate on what this means, or point me to the source code? I'd like to understand the broader concept and how it might affect us (ProdSec Insights rule devs).

> The advantage of the rules-based approach is that the rules-writers can 'know things' that the metadata doesn't, and therefore show implied relationships that the RPM-to-erratum and erratum-to-CVE metadata does not. vmaas-the-service can't - it only has available to it, the linkages that are explicit in the metadata. So there is a class of problem vmaas is good for, and a class of problem that rules are good for.

Aha, so it was meant generally about the two approaches, not about some very specific machinery inside the [insights-core](https://github.com/RedHatInsights/insights-core) proper. That I understand, and thank you for clarification. This discussion might have some value for posterity.
