### ISSUE TITLE
pkgtree - allow fetching of data for a single package name

### ISSUE THREAD

**Issue by jsvob** [RedHatInsights/vmaas#403]
Right now, pkgtree is a huge dictionary (json) like this:

```
{
    "timestamp": "2018-09-14T09:39:06.203197+00:00",
    "packages": {
        ...
        "openssl": [
            {
                "nevra": "openssl-1.0.0-4.el6.x86_64",
                ...
            },
            {
                ...
            },
        ],
        "openssl-libs": [
                ...
        ],
        ...
    }
}
```

It's currently at 100 MB with the repos I got from @eherget and https://github.com/RedHatInsights/vmaas/issues/399 mentions that there might be more repos. During the past 3 years, we've performed detection for tens of various package names - that would be a fraction of the data. Right now, remote data source functionality is being considered by insights-core.

I think that it might make sense to make it possible for the endpoint to return only the complete subtree for a single package name, say "openssl-libs". For that package, we do need the whole set of data, but we don't need anything for the thousands of other packages. In the end, we'd end up querying sth like tens or the low hundreds of various package names, with the possibility to add a new package name at any time (e.g. a new CSAw rule), and we'd never have the whole `insights-prodsec-rules->insights-core->vmaas` machinery download the other ~95 MB of data several times a day and it would also probably save significant amount of memory resources given the fact that the insights-core instances are duplicated by scaling in openshift (AFAIK).

Something simple, like GET `/{name}``, would be perfectly adequate. 

Still leaving the possibility to download the whole ~100MB pkgtree would be immensely useful during our development, so that we can grep through all the data and e.g. hunt down various details.

WDYT?
Thank you!

**Comment by eherget** [comment]
We got this running on our stage system where ~17k repos are scanned.  The resulting pkgtree file was nearly 4Gb in size!  We have opened an issue and created a task to gzip the output.  Since it is text, it will compress significantly.

As for the query by package name idea...

As you know, the data that is served up by VMaaS webapp component (the VMaaS API) has been pre-filtered to include only security related errata/CVE's.  Because of this it will not have all package data available.

Reposcan is the component that scans all the repos and builds the pre-filtered database dump that gets pushed to the webapp component.  Because reposcan is the only component that knows about all packages, we built the pkgtree "export" there.  The pkgtree file is built just after a scan of repos to gather any available updates.  I don't recall how often it scans, but in between scans, the data doesn't change.  Reposcan is not meant to be an API to get queried heavily or even, really, queried as part of an orchestrated flow.  We anticipated providing the pkgtree file to be downloaded at infrequent, regular intervals so that some other system could provide the data it contains for use in rules engines, etc.

As I mentioned before, seeing a 4Gb pkgtree file concerned us, so we are going to gzip it and see how significant the size reduction is.

For your per-packagename request, my initial thought would be a hope you could download the gzip'd pkgtree file and then either pre-process it to pull out only the data for the package names you need and/or build some service that consumes the pkgtree data and provides an API that would handle the GET /<packagename> query you mentioned.

I will bring this up with the team during our scrum tomorrow morning to see what other ideas we might come up with.

**Comment by eherget** [comment]
When we gzip the pkgtree file, it goes from about 3.2Gb to 90Mb using default compression.

**Comment by eherget** [comment]
The team discussed this during our scrum the other day and came up with some possible options to consider.  One of those options is to add a component to VMaaS, similar to webapp, that would consume the generated pkgtree and serve up responses to queries for packagename list of rpms.  If the interactive query functionality is extremely important, or if there might be more than one consumer of such a service, it must justify the work to implement.

Let's see how the gzip'd pkgtree output works, then continue this discussion if necessary.

**Comment by jsvob** [comment]
I understand and it makes sense. I'll bring it up on the next Insights weekly meeting and see whether the caching can be done on insights-core side.

**Comment by ggainey** [comment]
@eherget  - just had a thought - could we modify pkgtree, so that you could specify a list-of-names you cared about, and only generate the export for that list? If @jsvob only cares about small-tens of names, that might be a good compromise between 'deal with the whole plate' and 'be able to ask for one name at a time', yeah?

**Comment by jsvob** [comment]
@eherget @ggainey That would work for us, but only if there would be a way to add a new package in under a few hours, or if there is a second endpoint that does provide the full 4 GB of data. The whole 4 GB would be best because we could also grep for all related packages at the same time (e.g. like samba3x is for samba). Usecase for this - there's a new CSAw for a package we've never needed and we are under time pressure to produce a rule.

**Comment by jsvob** [comment]
As clarified in the recent email thread, I agree this should be a WONTFIX or NOTABUG. We (PS PIE & insights-core) should hash it out among ourselves and I agree that you (VMaaS) have already provided enough, and thank you for that.

Closing, since I was the one to open it.
