### ISSUE TITLE
Allow filtering results by "type"

### ISSUE THREAD

**Issue by dbaker-rh** [RedHatInsights/vmaas#421]
Ref: https://access.redhat.com/r/insights/docs/#api-Errata-GetErrata

Currently, insights allows filtering of results by severity (moderate, important, etc).

I would like the option to also filter results by type (bugfix, security, etc).

**Comment by tlestach** [comment]
Given the fact VMaaS provides only errata associated with a CVE (and RHSA without a CVE), all VMaaS provided errata are de facto security ones.
Current behavior is caused by the process if released errata are retrospectively identified as fixing CVEs, then those CVEs get associated with them post release (but the errata types cannot be changed anymore to RHSAs).

This request would make much more sense to me, if VMaaS was returning all of the RH released errata (RHSA, RHEA, RHBA) and not just those associated with an CVE.

I tend to nack this request.

**Comment by dbaker-rh** [comment]
I strongly believe this is a valid ask, but where it falls in the insights <--> vmaas handoff may be unclear.

When I run the query documented in the URL I referenced above, I get both security and bugfix results.

If it's nacked here, then where can I submit the issue so it gets traction?
