### ISSUE TITLE
ISE during module import

### ISSUE THREAD

**Issue by tkasparek** [RedHatInsights/vmaas#426]
Looks like something has changed in the modules.yaml

Internal server error <-9223363298951794907>'Traceback (most recent call last):\n  File "./reposcan.py", line 638, in run_task\n    repository_controller.store()\n  File "/git/repodata/repository_controller.py", line 254, in store\n    repository.load_metadata()\n  File "/git/repodata/repository.py", line 71, in load_metadata\n    self.modules = ModuleMD(self.md_files["modules"])\n  File "/git/repodata/modules.py", line 30, in __init__\n    module_dict[name][stream][\'artifacts\'] = data.get(\'artifacts\').get(\'rpms\', [])\nAttributeError: \'NoneType\' object has no attribute \'get\''

**Comment by ggainey** [comment]
@tkasparek this looks like the parsed-module-metadata didn't have a key, 'artifacts', so that data.get('artifacts') returned None, and the followon .get('rpms') therefore fails - does that make sense?

If so - my question is, what are 'artifacts'? Isn't the 'rpms' key a child of 'components'? (I'm reading here :  https://docs.fedoraproject.org/en-US/modularity/making-modules/defining-modules/ )

**Comment by jdobes** [comment]
Closing as no longer valid.
